name: Frontend CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'  # o la versión que uses

      - name: Install dependencies (Frontend)
        working-directory: ./fronted  # <-- Importante: Entra al directorio del frontend
        run: npm install

      - name: Run tests (Frontend)
        working-directory: ./fronted  # <-- Ejecuta los tests dentro de /fronted
        run: CI=true npm test
